name: shamo
description: Shoes Store App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.9
  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.0
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1
  http: ^0.13.4
  provider: ^6.0.2
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
